version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - python-backend
      - go-backend

  python-backend:
    build:
      context: ./python-backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - GO_BACKEND_URL=http://go-backend:8080
    volumes:
      - ./python-backend:/app
    depends_on:
      - postgres

  go-backend:
    build:
      context: ./go-backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=cloudtrim
      - POSTGRES_PASSWORD=cloudtrim
      - POSTGRES_DB=cloudtrim
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
